[package]
name = "profiler_builtins"
version = "0.0.0"
edition = "2021"

[lib]
test = false
bench = false
doc = false

[features]
default = ["core"]
core = ["dep:core", "dep:compiler_builtins"]

[dependencies]
core = { path = "../core", optional = true }
compiler_builtins = { version = "0.1.0", features = ['rustc-dep-of-std'], optional = true}

[build-dependencies]
cc = "1.2"
