[package]
name = "rustc_sanitizers"
version = "0.0.0"
edition = "2021"

[dependencies]
bitflags = "2.5.0"
tracing = "0.1"
twox-hash = "1.6.3"
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_hir = { path = "../rustc_hir" }
rustc_middle = { path = "../rustc_middle" }
rustc_span = { path = "../rustc_span" }
rustc_target = { path = "../rustc_target" }
rustc_trait_selection = { path = "../rustc_trait_selection" }

[features]
# tidy-alphabetical-start
rustc_use_parallel_compiler = ['rustc_data_structures/rustc_use_parallel_compiler']
# tidy-alphabetical-end
