[package]
name = "syntax"
version = "0.0.0"
description = "Comment and whitespace preserving parser for the Rust language"
repository = "https://github.com/rust-lang/rust-analyzer"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
either.workspace = true
itertools.workspace = true
rowan = "0.15.15"
rustc-hash.workspace = true
once_cell = "1.17.0"
indexmap.workspace = true
smol_str.workspace = true
triomphe.workspace = true
tracing.workspace = true

ra-ap-rustc_lexer.workspace = true

parser.workspace = true
stdx.workspace = true
text-edit.workspace = true

[dev-dependencies]
rayon.workspace = true
expect-test = "1.4.0"
proc-macro2 = "1.0.47"
quote = "1.0.20"
ungrammar = "1.16.1"

test-utils.workspace = true
sourcegen.workspace = true

[features]
in-rust-tree = []

[lints]
workspace = true
