nodeLinker: node-modules

plugins:
  - checksum: a6cb08da7dcaa17a72a2ebf584ffdc5fe391f928e75e644c3ad95dec16cb64ab532c42f672ce975a1b643b2227a9f1b74d4134ec886df82055ada15037bef173
    path: .yarn/plugins/@yarnpkg/plugin-cyclonedx.cjs
    spec: "https://github.com/CycloneDX/cyclonedx-node-yarn/releases/latest/download/yarn-plugin-cyclonedx.cjs"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
