# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "a7419818-36c0-4444-bce0-1d8d439b6052"
"safety-manager.cosign-bundle" = "c8c49b9e-eda9-4aff-8022-abe8556aab34"
"stable-archive.tar.gz" = "42e3ffb2-ba8a-4b35-8343-809ffb0bb55e"
