# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

---

name: CI
on:
  pull_request:
  merge_group:

# Defined at the job level.
permissions: {}

jobs:
  build:
    name: Build the documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Build documentation and check links
        run: ./make.py --check-links

      - name: Verify licensing metadata
        run: uvx reuse lint

      - name: Verify Python code formatting
        run: uvx black . --check --diff --color

      - name: Lint Python code with flake8
        run: uvx flake8 . --exclude .venv

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/html

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.event_name == 'merge_group'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment

  finished:
    name: CI finished
    runs-on: ubuntu-latest
    needs: [ build, deploy ]
    if: "${{ !cancelled() }}"
    env:
      NEEDS: "${{ toJson(needs) }}"
    steps:
      - name: Check if all jobs were successful or skipped
        run: echo "${NEEDS}" | jq --exit-status 'all(.result == "success" or .result == "skipped")'
