# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[roles.safety-manager]
role-name = "Safety Manager"
name = "Florian Gilcher"
email = "florian.gilcher@ferrous-systems.com"
