# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "6361a234-d205-485c-aa4d-9f8074153168"
"safety-manager.cosign-bundle" = "f07f7674-d6da-42f6-8d25-bdc2bd40eba0"
