<<<PULL-UPSTREAM>>> file deleted upstream; fix the conflict and remove this line
# ignore-cross-compile
include ../tools.mk

all:
	$(RUSTC) main.rs -C opt-level=1
	$(call RUN,main)

# ferrocene-annotations: um_rustc_C_opt_level
