# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[theme]
inherit = "basic"
stylesheets = ["ferrocene.css"]

[options]
license = ""
commit = ""
include_in_header = ""
