# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

# This uses CircleCI's dynamic configuration feature to calculate some
# parameters before executing the workflows. You're probably looking for
# `.circleci/workflows.yml` if you need to change the CI configuration.

---
version: 2.1
setup: true

parameters:
  # use this parameter to disable building the windows host. This is useful to cut down build times and
  # cost in cases where you want to experiment with linux builds and are not interested in windows results
  full-build-x86_64-pc-windows-msvc-host:
    type: boolean
    default: true
  # use this parameter to disable building the darwin host. This is useful to cut down build times and
  # cost in cases where you want to experiment with linux builds and are not interested in darwin results
  full-build-aarch64-darwin-host:
    type: boolean
    default: true

orbs:
  ferrocene: ferrocene/ferrocene-common@26080.3.0 # https://circleci.com/developer/orbs/orb/ferrocene/ferrocene-common?version=26080.3.0#orb-source
  continuation: circleci/continuation@0.2.0

jobs:
  setup:
    docker:
    # We can't use our own mechanism to install aws-cli in our preferred version here because
    # this is the workflow that reads our preferred version and calculates that paramter. So
    # We use cimg/aws which comes with a somewhat recent version of aws-cli
      - image: cimg/aws:2026.07
    resource_class: ferrocene/k8s-arm64-small # 1-core
    steps:
      - ferrocene/aws_oidc_auth
      - ferrocene/git_shallow_clone:
          depth: 1
      - ferrocene/setup_uv

      - run:
          name: Calculate the parameters for the workflow
          command: |
            ferrocene/ci/scripts/calculate_parameters.py > /tmp/continue-parameters.json
            cat /tmp/continue-parameters.json
          environment:
            FULL_BUILD_X86_64_WINDOWS_MSVC: << pipeline.parameters.full-build-x86_64-pc-windows-msvc-host >>
            FULL_BUILD_AARCH64_DARWIN: << pipeline.parameters.full-build-aarch64-darwin-host >>

      - continuation/continue:
          configuration_path: .circleci/workflows.yml
          parameters: /tmp/continue-parameters.json

      - run:
          name: Wait for continuation job to complete
          command: ferrocene/ci/wait-for-pipeline.sh

workflows:
  version: 2
  setup:
    when:
      or:
        - equal: [<< pipeline.git.branch >>, "staging"]
        - equal: [<< pipeline.git.branch >>, "trying"]
        - equal: [<< pipeline.trigger_source >>, "api"]
        - equal: [<< pipeline.git.branch >>, automation/bors/auto]
        - equal: [<< pipeline.git.branch >>, automation/bors/try]
    jobs: [setup]
