[package]
name = "proc-macro-srv"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
object.workspace = true
libloading = "0.8.0"
memmap2 = "0.5.4"

stdx.workspace = true
tt.workspace = true
mbe.workspace = true
paths.workspace = true
base-db.workspace = true
span.workspace = true
proc-macro-api.workspace = true
ra-ap-rustc_lexer.workspace = true

[dev-dependencies]
expect-test = "1.4.0"

# used as proc macro test targets
proc-macro-test.path = "./proc-macro-test"

[features]
sysroot-abi = []
in-rust-tree = ["mbe/in-rust-tree", "sysroot-abi"]

[lints]
workspace = true
