// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: The Ferrocene Developers

use std::fs::DirEntry;
use std::path::Path;

use crate::builder::Builder;

// Scan the build directory for a given stage, and iterate over all the files within.
//
// As of https://github.com/rust-lang/rust/pull/155439 (upstream commit 210119ba),
// the build directories generated by Cargo look like:
// build/TARGET/STAGE/dist/build/CRATE/HASH/fingerprint/{files...}
// build/TARGET/STAGE/dist/build/CRATE/HASH/out/{files...}
//
// The `stage_out` argument here should be the result of builder.cargo_out() or similar,
// which builds the path up to `dist`, and this function takes care of the rest.
pub(crate) fn scan_build_tree(
    builder: &Builder<'_>,
    stage_out: &Path,
) -> impl Iterator<Item = DirEntry> {
    builder
        .read_dir(&stage_out.join("build"))
        .flat_map(|e| builder.read_dir(&e.path()))
        .flat_map(|e| builder.read_dir(&e.path()))
        .flat_map(|e| builder.read_dir(&e.path()))
}
