[package]
name = "flycheck"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
cargo_metadata.workspace = true
crossbeam-channel.workspace = true
tracing.workspace = true
rustc-hash.workspace = true
serde_json.workspace = true
serde.workspace = true
process-wrap.workspace = true

# local deps
paths.workspace = true
stdx.workspace = true
toolchain.workspace = true
project-model.workspace = true

[lints]
workspace = true