FROM bitriseio/docker-android

ENV CARGO_TARGET_ARM_LINUX_ANDROIDEABI_LINKER=arm-linux-androideabi-gcc \
    # TODO: should actually run android tests in an emulator
    CARGO_TARGET_ARM_LINUX_ANDROIDEABI_RUNNER=true
