# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "a09c467a-45ab-477f-8687-5b2c19b7aa69"
"safety-manager.cosign-bundle" = "0c55c503-a41b-4099-a514-3cfd968e7f18"
