[package]
name = "project-model"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
cargo_metadata.workspace = true
rustc-hash.workspace = true
semver.workspace = true
serde_json.workspace = true
serde.workspace = true
tracing.workspace = true
triomphe.workspace = true
la-arena.workspace = true
itertools.workspace = true

# local deps
base-db.workspace = true
cfg.workspace = true
paths.workspace = true
stdx.workspace = true
toolchain.workspace = true

[dev-dependencies]
expect-test = "1.4.0"

[lints]
workspace = true
