[package]
name = "rustc_ast_pretty"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
itertools.workspace = true
rustc_ast = { path = "../rustc_ast" }
rustc_lexer = { path = "../rustc_lexer" }
rustc_span = { path = "../rustc_span" }
# tidy-alphabetical-end

[dev-dependencies]
# tidy-alphabetical-start
thin-vec.workspace = true
# tidy-alphabetical-end
