name: "Restore build cache"
description: "Restore build cache from an artifact. Resets mtime, restores removed symlinks..."
inputs:
  build-run-id:
    description: The run id of the build workflow
  build-artifact:
    description: The artifact from the build workflow

runs:
  using: "composite"
  steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build-artifact }}
        run-id: ${{ inputs.build-run-id }}
    - name: Post artifact download steps
      shell: bash
      run: uv run ./ferrocene/ci/scripts/build_cache.py post-download
    - name: Remove old build cache tar
      shell: bash
      run: rm -rf build.tar
