[package]
name = "rustc_ast"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
bitflags.workspace = true
memchr.workspace = true
rustc-literal-escaper.workspace = true
rustc_ast_ir = { path = "../rustc_ast_ir" }
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_index = { path = "../rustc_index" }
rustc_macros = { path = "../rustc_macros" }
rustc_serialize = { path = "../rustc_serialize" }
rustc_span = { path = "../rustc_span" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec.workspace = true
tracing = "0.1"
# tidy-alphabetical-end
