# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "8e9acf04-124f-4c96-b4e7-195541ab707c"
"safety-manager.cosign-bundle" = "3574e3a3-54e6-4426-9907-e530c092b47d"
"stable-archive.tar.gz" = "cadf013a-fd62-47f4-9c9c-a6e5dad67e81"
