# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "9cf2cd07-04dc-40ae-aecb-cb5aaa45f422"
"safety-manager.cosign-bundle" = "b726a423-7616-4fb1-bd87-a4a9afa115c3"
