#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

set -euxo pipefail
IFS=$'\n\t'

if ! mergiraf --version >/dev/null 2>&1; then
    echo "Need 'mergiraf' installed to automatically fix merge conflicts"
    exit 1
fi

for file in "$@"; do
    # Print the name of the file, just in case it takes long to resolve
    # (for easier debugging)
    echo "fix-merge: trying to resolve conflict for ${file} using mergiraf..."
    # - Don't keep backups of the original files, since they are
    #   available in the previous commit.
    # - `solve` returns 2 when not all conflicts have been resolved --
    #   add `|| true` to avoid exiting the script because of that
    mergiraf solve --keep-backup=false "$file" || true
done

# Only commit if mergiraf has resolved anything
if git status --porcelain=v1 | grep "^ M " >/dev/null; then
    # If mergiraf wasn't able to make any progress on the conflict, or if it
    # encountered an error during the resolution, it will leave the input
    # file unchanged. Therefore, everything that was changed is good to add.
    git add .

    git commit -F- <<EOF
resolve conflicts using mergiraf

This commit is generated by \`ferrocene/tools/fix-merge/fix-merge.sh\`.
EOF
fi
