#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

set -euxo pipefail
IFS=$'\n\t'

LOCAL_REPO_ROOT=$(git rev-parse --show-toplevel)
cd "${LOCAL_REPO_ROOT}"

if [ $# -ne 1 ]; then
    echo "Usage: $0 <ferrocene branch name>"
    exit 2
fi

branch_name="$1"

# Check for MacOS sed, which doesn't support `-i`.
if [ "$(uname)" = Darwin ]; then
    if ! gsed --version >/dev/null 2>&1; then
        echo "Need 'gsed' installed; try 'brew install gnu-sed'"
        exit 1
    fi
    sed=gsed
else
    sed=sed
fi

if ! mergiraf --version >/dev/null 2>&1; then
    echo "Need 'mergiraf' installed to automatically fix merge conflicts"
    exit 1
fi

# We do a `git submodule update` ahead of time to ensure the wrong
# submodule commits are not accidentally added.
git submodule update --recursive

# The person handling the conflict should decide what to do if a file
# has been deleted on either side of the merge, but doing a `git add .`
# would mask the conflict (it would simply revert the deletion).
#
# To avoid that, we prefix the file with a custom line noting the file
# had a delete conflict, and the detect-conflict-markers.py script will
# pick it up and block CI until it's resolved either way.
handle_deleted_files() {
    marker="$1"
    who="$2"
    for changed_file in $(git status --porcelain=v1 | sed -n "s/^${marker} //p"); do
        $sed -i "1s/^/<<<PULL-UPSTREAM>>> file deleted ${who}; move the Ferrocene annotations if any, and delete this file\\n/" "${changed_file}"
    done
}
handle_deleted_files DU "in Ferrocene" # DU means "deleted by us"
handle_deleted_files UD "upstream"     # UD means "deleted by them"

# Save the list of still conflicted files to try to later resolve with
# mergiraf. Exclude the deleted files, since mergiraf can't really
# resolve them (and because it spams about parse errors caused by
# <<<PULL-UPSTREAM>>>) -- but don't bother excluding the files deleted
# by us, since those are a rare occurrance.
#
# The awk invocation:
# - includes files that are unmerged ("u")
# - excludes files that are "deleted by them" ("UD")
# - prints the file name (last column of the output of `git status --porcelain=v2`)
files=$(git status --porcelain=v2 | awk '$1 == "u" && $2 != "UD" {print $NF}')

git diff --name-only | xargs $sed -i "s#<<<<<<< HEAD#<<<<<<< ferrocene/${branch_name}#"
git add .

# Setting the editor to `true` prevents the actual editor from being open,
# as in this case we don't want to change the default message.
GIT_EDITOR="$(which true)" git merge --continue

# Try resolving conflicted files using mergiraf.
if [ -n "$files" ]; then
    for file in $files; do
        # Print the name of the file, just in case it takes long to resolve
        # (for easier debugging)
        echo "fix-merge: trying to resolve conflict for ${file} using mergiraf..."
        # - Don't keep backups of the original files, since they are
        #   available in the previous commit.
        # - `solve` returns 2 when not all conflicts have been resolved --
        #   add `|| true` to avoid exiting the script because of that
        mergiraf solve --keep-backup=false "$file" || true
    done

    # Only commit if mergiraf has resolved anything
    if git status --porcelain=v1 | grep "^ M " >/dev/null; then
        # If mergiraf wasn't able to make any progress on the conflict, or if it
        # encountered an error during the resolution, it will leave the input
        # file unchanged. Therefore, everything that was changed is good to add.
        git add .

        git commit -F- <<EOF
resolve conflicts using mergiraf

This commit is generated by \`ferrocene/tools/fix-merge/fix-merge.sh\`.
EOF
    fi
fi
