[package]
name = "rustc_index"
version = "0.0.0"
edition = "2021"

[dependencies]
# tidy-alphabetical-start
arrayvec = { version = "0.7", default-features = false }
rustc_index_macros = { path = "../rustc_index_macros", default-features = false }
rustc_macros = { path = "../rustc_macros", optional = true }
rustc_serialize = { path = "../rustc_serialize", optional = true }
smallvec = "1.8.1"
# tidy-alphabetical-end

[features]
# tidy-alphabetical-start
default = ["nightly"]
nightly = [
    "dep:rustc_serialize",
    "dep:rustc_macros",
    "rustc_index_macros/nightly",
]
# tidy-alphabetical-end
