[package]
name = "rustc_transmute"
version = "0.0.0"
edition = "2021"

[dependencies]
# tidy-alphabetical-start
rustc_ast_ir = { path = "../rustc_ast_ir", optional = true }
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_hir = { path = "../rustc_hir", optional = true }
rustc_infer = { path = "../rustc_infer", optional = true }
rustc_macros = { path = "../rustc_macros", optional = true }
rustc_middle = { path = "../rustc_middle", optional = true }
rustc_span = { path = "../rustc_span", optional = true }
rustc_target = { path = "../rustc_target", optional = true }
tracing = "0.1"
# tidy-alphabetical-end

[features]
rustc = [
    "rustc_hir",
    "rustc_infer",
    "rustc_macros",
    "rustc_middle",
    "rustc_span",
    "rustc_target",
    "rustc_ast_ir",
]

[dev-dependencies]
# tidy-alphabetical-start
itertools = "0.11"
# tidy-alphabetical-end
