# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "22350323-3e91-44af-a122-a1301ef18b8e"
"safety-manager.cosign-bundle" = "0b24f87a-41db-40ab-a9c2-94cb0a78fca1"
