# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "1d207726-252e-4f7f-9650-763bcf51d564"
"safety-manager.cosign-bundle" = "8536c7dd-5fed-4035-a729-6d58b6391d14"
