# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "dba904e5-00a4-49c4-865c-2eaba53ba9f2"
"safety-manager.cosign-bundle" = "28adab17-8cac-4cbf-8f3f-369b90444264"
