#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

# This script generates the contents of a simple GitHub Pages site containing
# the documentation for the current commit, plus other reports generated by CI
# for that commit. This is not meant to be customer-facing, it's just a simple
# small internal thing to help our developers view the current state of things.

import os
import subprocess
import tempfile
import tomli


ARTIFACTS_PREFIX = "s3://ferrocene-ci-artifacts/ferrocene/dist"
ONLY_SUBSETS = {"default"}


def run(branch, *, redirect_from_index=False):
    output = tempfile.mkdtemp()
    os.makedirs(f"{output}/{branch}", exist_ok=True)
    commit = cmd("git", "rev-parse", branch, stdout=True).strip()

    # GitHub Pages requires all the files to have readable permissions,
    # otherwise the deploy will error out. For us, the only problem is the root
    # directory not being world-readable. See:
    # https://github.com/actions/deploy-pages/issues/188
    os.chmod(output, 0o755)

    with tempfile.TemporaryDirectory() as download_dir:
        for tarball, directory_inside in get_docs_tarballs():
            cmd(
                "aws",
                "s3",
                "cp",
                f"{ARTIFACTS_PREFIX}/{commit}/{tarball}",
                f"{download_dir}/{tarball}",
            )
            cmd(
                "tar",
                "xJf",
                f"{download_dir}/{tarball}",
                "-C",
                f"{output}/{branch}",
                "--strip-components",
                str(directory_inside.count("/") + 1),
                directory_inside,
            )

    generate_redirect(
        output,
        f"{branch}/traceability-matrix-x86_64-unknown-linux-gnu.html",
        f"/{branch}/qualification/traceability-matrix.html",
    )

    if redirect_from_index:
        generate_redirect(
            output,
            "index.html",
            f"{branch}/index.html",
        )

    with open(os.environ["GITHUB_OUTPUT"], "a") as f:
        f.write(f"dir={output}\n")


def generate_redirect(output, src, dest):
    with open(f"{output}/{src}", "w") as f:
        f.write(
            f'<!DOCTYPE html>\n<meta charset="utf-8">\n<script>location.pathname = "{dest}";</script>\n'
        )


def get_docs_tarballs():
    with open("ferrocene/packages.toml", "rb") as f:
        packages = tomli.load(f)

    commit_hash = cmd("git", "rev-parse", "--short=9", "HEAD", stdout=True)

    for group in packages["groups"].values():
        for package in group["packages"]:
            try:
                docs_in = package["docs-in"]
            except KeyError:
                continue
            if package["subset"] not in ONLY_SUBSETS:
                continue

            if "*" not in group["targets"]:
                raise RuntimeError("target-specific docs not supported")
            yield f"{package['name']}-{commit_hash}.tar.xz", docs_in


def cmd(*args, stdout=False):
    options = {}
    if stdout:
        options["stdout"] = subprocess.PIPE
        options["text"] = True

    result = subprocess.run(args, check=True, **options)
    if stdout:
        return result.stdout


if __name__ == "__main__":
    run("main", redirect_from_index=True)
