# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "d64c0145-3889-46dd-9fd6-dfff37f1e991"
"safety-manager.cosign-bundle" = "3341a724-53d5-4244-a4d9-191c941f0645"
