[package]
name = "run_make_support"
version = "0.2.0"
edition = "2021"

[dependencies]
bstr = "1.12"
object = "0.37"
similar = "2.7"
wasmparser = { version = "0.219", default-features = false, features = ["std"] }
regex = "1.11"
gimli = "0.32"
build_helper = { path = "../../build_helper" }
serde_json = "1.0"
libc = "0.2"

[lib]
crate-type = ["lib", "dylib"]
