[package]
name = "hir-expand"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
tracing.workspace = true
either.workspace = true
rustc-hash.workspace = true
la-arena.workspace = true
itertools.workspace = true
hashbrown.workspace = true
smallvec.workspace = true
triomphe.workspace = true

# local deps
stdx.workspace = true
intern.workspace = true
base-db.workspace = true
cfg.workspace = true
syntax.workspace = true
tt.workspace = true
mbe.workspace = true
limit.workspace = true
span.workspace = true

[dev-dependencies]
expect-test = "1.4.0"

[lints]
workspace = true
