name: Self-Test
run-name: Self-Test (${{inputs.host-triple}})

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      host-triple:
        type: string
        description: The Rust triple of the host platform
      triples:
        type: string
        description: The target triples to test
      runner:
        type: string
        description: The GitHub Runner to run on
      build-run-id:
        type: string
        description: The run id of the build workflow
      build-artifact:
        type: string
        description: The artifact from the build workflow
      container:
        type: string
        description: The container URI to run the build in, if any (Linux only)
      environment:
        type: string

jobs:

  self-test:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    env:
      FERROCENE_HOST: ${{ inputs.host-triple }}
      FERROCENE_BUILD_HOST: ${{ inputs.host-triple }}
      FERROCENE_TARGETS: ${{ inputs.triples }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup/
        with:
          build-dependencies: ${{ (inputs.container != '') && 'false' || 'true' }}

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ (github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/hoverbear/gha-migration') && secrets.AZURE_OIDC_GHA_CLIENT_ID_STAGING || secrets.AZURE_OIDC_GHA_CLIENT_ID_TRYING }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # https://github.com/Azure/login/issues/372#issuecomment-2056289617
      - name: Cache Azure storage token
        run: az account get-access-token --scope https://storage.azure.com/.default --output none 
      - name: Authenicate docker with Azure
        if: ${{ (runner.os == 'Linux') }}
        run: az acr login --name ferrocenecr

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume:  ${{ (github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/hoverbear/gha-migration') && secrets.AWS_OIDC_GHA_ARN_STAGING || secrets.AWS_OIDC_GHA_ARN_TRYING }}

      - name: Download QNX
        id: qnx
        uses: ./.github/actions/qnx/
        with:
          version: "7.1.0-472"

      - name: Run
        uses: ./.github/actions/run/
        with:
          container: ${{ inputs.container }}
          script: |
            export QNX_LICENSE_FILE="${{ steps.qnx.outputs.directory }}/license/licenses"
            source ${{ steps.qnx.outputs.directory }}/qnxsdp-env.sh

            ferrocene/ci/scripts/run-self-test.sh

